# FROM riscv64/ubuntu:latest AS base-amd64
FROM ubuntu:22.04 AS build-stage

ARG DEBIAN_FRONTEND=noninteractive
RUN <<EOF
set -e
apt update
apt install -y --no-install-recommends \
    build-essential=12.9ubuntu3 \
    ca-certificates \
    g++-riscv64-linux-gnu=4:11.2.0--1ubuntu1 \
    wget
EOF

ARG GOVERSION=1.23.5

WORKDIR /opt/build

RUN wget https://go.dev/dl/go${GOVERSION}.linux-$(dpkg --print-architecture).tar.gz && \
  tar -C /usr/local -xzf go${GOVERSION}.linux-$(dpkg --print-architecture).tar.gz

ENV GOOS=linux
ENV GOARCH=riscv64
ENV CGO_ENABLED=1
# ENV CGO_ENABLED=0
ENV CC=riscv64-linux-gnu-gcc
ENV CXX=riscv64-linux-gnu-g++
ENV PATH=/usr/local/go/bin:${PATH}

COPY . .

# RUN go generate ./...
# RUN go build .
RUN apt-get update
RUN apt-get install -y cmake ccache
# RUN cmake --preset CPU -DCMAKE_CXX_FLAGS="-march=riscv64"
RUN cmake --preset CPU -DCMAKE_CXX_FLAGS="-march=rv64gc"
# RUN cmake --preset CPU --trace-expand | grep 'CMAKE_CXX_FLAGS'
RUN cmake --build --preset CPU --parallel
